sq/JSIL

Libraries/JSIL.js
Tests/EmscriptenTestCases/OutUshortArrayParameter.cs
Tests/EmscriptenTestCases/PassDelegateInStruct.cs
Tests/EmscriptenTestCases/PassFlagsInStruct.cs
Tests/EmscriptenTestCases/common/common.cpp
Tests/EmscriptenTestCases/embuild.bat
Tests/Tests.csproj

Some tests for compatibility features needed by FNA

FNA-derived compatibility tests

---

Libraries/JSIL.Core.js
Libraries/JSIL.PInvoke.js
Libraries/JSIL.Unsafe.js

Emit unimplemented marshalling type errors as warnings until they're actually an issue

Emscripten delayed error

---

Tests/EmscriptenTestCases/StructAlignment.cs
Tests/EmscriptenTestCases/common/common.cpp
Tests/Tests.csproj

Add StructAlignment test for enum alignment

---

JSIL/Transforms/DecomposeMutationOperators.cs
Tests/SimpleTestCases/RefIntIncrement_Issue684.cs
Tests/SimpleTests.csproj

Ref Integer increment issue fixed.

---

JSIL/Transforms/DecomposeMutationOperators.cs
Tests/Tests.csproj
Tests/UnsafeTestCases/PointerWriteConversion_Issue686.cs

Fixed issue with pointer write conversion.

---

Tests/Tests.csproj

Sorry, once again forget to fix test default build action :)

Fixed build action for PointerWriteConversion.

---

Tests/ComparisonTest.cs
Tests/EmscriptenTestCases/ProxiedExternFunction.cs
Tests/EmscriptenTests.cs
Tests/GenericTestFixture.cs
Tests/Tests.csproj

Test for bug in proxying extern methods

---

Tests/EmscriptenTestCases/PassPtrToPinnedArray.cs
Tests/EmscriptenTestCases/common/common.cpp
Tests/Tests.csproj

Add test for passing GCHandle ptr to emscripten

---

.gitattributes

Small addition, corresponds with the .hgeol file to enforce EOL

Added git attributes file to enforce normalized EOL

---

JSIL/AssemblyManifest.cs

AssemblyId generation use lock.

---

Try/Try.csproj

Fixed compile error (annoying as breaks CI).

Removed from Try project delted OAuth.cs to fix compilation.

---

Libraries/JSIL.Bootstrap.js
Tests/SimpleTestCases/HashSetSameHash_Issue752.cs
Tests/SimpleTests.csproj

Fix skipping values in HashSet.

---

Compiler/Program.cs
JSIL/AssemblyTranslator.cs
JSIL/CILSupport.cs
Tests/ComparisonTest.cs

@kg, please answer #763. This is suggest patch if it was a bug.

Same caching metadata resolver

---

JSIL.Libraries/Includes/Bootstrap/Core/Utils/$jsilcore.$ParseBoolean.js

Added null check to boolean parsing

---

JSIL.Libraries/Sources/JSIL.Core.Types.js
JSIL.Libraries/Sources/JSIL.Core.js
Tests/SimpleTestCases/NumericTypesBase_Issue812.cs
Tests/SimpleTestCases/RawTypeIsObject_Issue754.cs
Tests/SimpleTests.csproj

Fixed object check for boolean (#754) and base type for numeric types (#812).

Numeric fixes

---

JSIL.Libraries/gulpfile.js
JSIL.Libraries/package.json

Header for generated scripts, generated scripts are readonly (#818).

Header for generated scripts, generated scripts are readonly

---

JSIL.Libraries/gulpfile.js

Fix gulp script (run metascript after clean).

---

JSIL.Libraries/Includes/Bootstrap/Core/Classes/System.Delegate.js
JSIL/AST/JSExpressionTypes.cs
JSIL/ILBlockTranslator.cs
JSIL/JavascriptAstEmitter.cs
JSIL/SpecialIdentifiers.cs
Tests/SimpleTestCases/DelegateOverload_Issue806.cs
Tests/SimpleTests.csproj

Here is fix for #806 and test for it.

Invocation overloaded method through delegate.

---

JSIL.Libraries/gulpfile.js
JSIL.Libraries/package.json

Translated scripts should contain BOM at the beginning.

---

appveyor.yml

Added config for ci.appveyor.com.

---

JSIL.Libraries/Includes/Bootstrap/Core/Classes/System.Collections.Concurrent.ConcurrentQueue.js
JSIL.Libraries/Includes/Bootstrap/Core/Classes/System.Threading.SemaphoreSlim.js
JSIL.Libraries/Includes/Bootstrap/Core/Main.js
JSIL.Libraries/Includes/Bootstrap/DateTime/Classes/System.DateTime.js
JSIL.Libraries/Includes/Bootstrap/Linq/Classes/System.Linq.Expressions.BinaryExpression.js
JSIL.Libraries/Includes/Bootstrap/Linq/Main.js
JSIL.Libraries/Includes/Core/Reflection/Classes/System.Reflection.Assembly.js
JSIL.Libraries/Includes/Core/Reflection/Classes/System.Reflection.CustomAttributeExtensions.js
JSIL.Libraries/Includes/Core/Reflection/Classes/System.Reflection.IntrospectionExtensions.js
JSIL.Libraries/Includes/Core/Reflection/Classes/System.Reflection.TypeInfo.js
JSIL.Libraries/Includes/Core/Reflection/Main.js
JSIL.Libraries/Includes/IO/Classes/System.IO.Path.js
JSIL.Libraries/Includes/IO/Classes/System.IO.Stream.js
JSIL.Libraries/Includes/XML/Classes/System.Xml.XmlReader.js
JSIL.Libraries/JSIL.Libraries.csproj
JSIL.Libraries/Sources/JSIL.js
Proxies/BCL/JSIL.Bootstrap.DateTime.cs
Proxies/String.cs

Redo of #813. I added some more implementations I've done since then,too.

Misc. implementations

---

JSIL.Libraries/Sources/JSIL.Core.js
Tests/SimpleTestCases/StringFromCtor.cs
Tests/SimpleTests.csproj

String primitive

---

JSIL.Libraries/Includes/Bootstrap/Core/Classes/System.Boolean.js
JSIL.Libraries/Includes/Bootstrap/Core/Classes/System.Byte.js
JSIL.Libraries/Includes/Bootstrap/Core/Classes/System.Char.js
JSIL.Libraries/Includes/Bootstrap/Core/Classes/System.Double.js
JSIL.Libraries/Includes/Bootstrap/Core/Classes/System.Int16.js
JSIL.Libraries/Includes/Bootstrap/Core/Classes/System.Int32.js
JSIL.Libraries/Includes/Bootstrap/Core/Classes/System.SByte.js
JSIL.Libraries/Includes/Bootstrap/Core/Classes/System.Single.js
JSIL.Libraries/Includes/Bootstrap/Core/Classes/System.UInt16.js
JSIL.Libraries/Includes/Bootstrap/Core/Classes/System.UInt32.js
JSIL.Libraries/Includes/Core/Reflection/Classes/System.Reflection.FieldInfo.js
JSIL.Libraries/Includes/Core/Reflection/Classes/System.Reflection.MethodInfo.js
JSIL.Libraries/Includes/Reference/Classes/JSIL.Box.js
JSIL.Libraries/Includes/Reference/Main.js
JSIL.Libraries/JSIL.Libraries.csproj
JSIL.Libraries/Sources/JSIL.Core.js
JSIL/AST/JSExpressionTypes.cs
JSIL/ILBlockTranslator.cs
JSIL/JavascriptAstEmitter.cs
Proxies/Numbers.cs
Tests/SimpleTestCases/ResolveWrappedNumericType.cs
Tests/SimpleTests.csproj

New version for numeric type boxing. This PR should be now looked instead of #773.

Box for Numeric types.

---

JSIL/DynamicCallSites.cs
JSIL/ILBlockTranslator.cs

Introduced generic forms for Verbatium.Expression to prevent boxing.
It will help solve problem that I described in #773.

Verbatium.Expression generic

---

JSIL.Libraries/Includes/Bootstrap/Core/Helpers/JSIL.GetEnumerator.js
Tests/SimpleTestCases/Array2DGetEnumerator_Issue895.cs
Tests/SimpleTests.csproj

GetEnumerator for multidimensional arrays fixed.

---

JSIL.Libraries/Sources/JSIL.Core.js

Issue #876 - Fixed typo

---

JSIL/JavascriptAssemblyEmitter.cs
Tests.DCE/DCETests/StripInterfaceImplementation.cs
Tests.DCE/DeadCodeEliminationTest.cs
Tests.DCE/Tests.DCE.csproj

When DCE stripped interface, I missed to strip it from another interface implemented interfaces list. Here is fix and test case added.

Fixed output with DCE enabled

---

JSIL.Libraries/Sources/JSIL.Core.js
Tests/SimpleTestCases/Issue866.cs
Tests/SimpleTests.csproj

Workaround for type initialization (#866). Test case added.

Initialize type if not yet on IsAssignableFrom.

---

JSIL.Libraries/Sources/JSIL.Core.js
Tests/SimpleTestCases/ArrayCloneNative_Issue932.cs
Tests/SimpleTests.csproj

Fixed issue #932 and test added.

Fixed Array.Clone with native JS arrays

---

JSIL/TypeInformation.cs
Tests/ComparisonTests.cs
Tests/FormattingTests.cs
Tests/SpecialTestCases/RoslynBigStringSwitchWithStaticArray.cs
Tests/Tests.csproj

Fix for  (#921) and test added.
@kg, please wait for CI build finish before merge.

Sting switch statement on Roslyn

---

JSIL/AST/JSAstVisitor.cs
JSIL/AST/JSNodeTypes.cs
JSIL/FunctionTransformPipeline.cs
JSIL/ILBlockTranslator.cs
JSIL/JSIL.csproj
JSIL/JavascriptAstEmitter.cs
JSIL/SourceMapBuilder.cs
JSIL/Transforms/AttachSymbolInfoToStatements.cs
JSIL/Transforms/FixSymbolInfo.cs

With this PR source map generated by JSIL is much more usable.

Improved source map generation

---

JSIL/AssemblyTranslator.cs
JSIL/ILBlockTranslator.cs

Fix false warning during compilation

---

JSIL.Libraries/Sources/JSIL.Core.js

Implemented support for signature inline cache for interface with fallbacks, as part of #978 .

Signature inline cache for interface with fallback

---

JSIL.Libraries/Includes/Bootstrap/DateTime/Classes/System.DateTime.js
JSIL.Libraries/Sources/JSIL.Host.js

Fixed DateTime.Now and DateTime.UtcNow (#511).

Fixed DateTime.Now and DateTime.UtcNow

---

JSIL/ILBlockTranslator.cs
Tests/SimpleTestCases/NullableUnary_Issue997.cs
Tests/SimpleTests.csproj

Fixed translation of unary operations with nullable

---

JSIL/DefinitelyTypedAssemblyEmitter.cs
JSIL/JS Libraries/DefinitelyTyped/internals/JSIL.Core.d.ts

Added variance support for *.d.ts declarations. Fixed some issue.

Variance support for d.ts

---

JSIL.Libraries/Sources/JSIL.Core.js
Tests/SimpleTestCasesForTranslatedBcl/Issue1008_MethodReturnType.cs
Tests/SimpleTests.csproj

Correct type resolution for arrays. Fix #1008.

Correct type resolution for arrays

---

JSIL.Libraries/Includes/Core/Reflection/Classes/System.Type.js

Type.IsInstanceOfType implemented.

Type.IsInstanceOfType implemented

---

Tests/SimpleTestCasesForTranslatedBcl/Issue1008_MethodReturnType.cs

Change test-case for mono compatibility.

Change test-case for mono compatibility

---

JSIL.Libraries/Includes/Bootstrap/Text/Classes/System.String.js
Proxies/String.cs

This implements the String.Insert function

String insert

---

JSIL.Libraries/Includes/Bootstrap/Async/Classes/System.AggregateException.js
JSIL.Libraries/Includes/Bootstrap/Async/Classes/System.OperationCanceledException.js
JSIL.Libraries/Includes/Bootstrap/Async/Classes/System.Runtime.CompilerServices.TaskAwaiter.js
JSIL.Libraries/Includes/Bootstrap/Async/Classes/System.Threading.Tasks.Task.js
JSIL.Libraries/Includes/Bootstrap/Async/Classes/System.Threading.Tasks.TaskCanceledException.js
JSIL.Libraries/Includes/Bootstrap/Async/Main.js
JSIL.Libraries/JSIL.Libraries.csproj
Tests/SimpleTestCases/Task_FromResult.cs
Tests/SimpleTests.csproj

Implementation of Task.FromResult<TResult>(TResult result).
Added support for task cancellation.

Async improvements
