sq/JSIL

- Tests/EmscriptenTestCases/PassDelegateInStruct.cs
- Tests/EmscriptenTestCases/common/common.cpp
"Uncaught RangeError: start offset of Int32Array should be a multiple of 4"
Only seems to happen for the struct which also has a function pointer.
> PassDelegateInStruct fails with ushort in struct

- Libraries/JSIL.Core.js
- Tests/SimpleTestCases/Issue560.cs
- Tests/SimpleTests.csproj
Fixes #560 by adding a special case version of _IsAssignableFrom for System.Object
> IsAssignableFrom always true for Object (#560)

- JSIL/Util.cs
- Tests/SimpleTestCases/StringEscape_Issue687.cs
- Tests/SimpleTests.csproj
> Fixed incorrect string escape for null-byte following digit char.

- JSIL/AssemblyTranslator.cs
- JSIL/JavascriptAstEmitter.cs
- JSIL/Util.cs
- Tests/ComparisonTest.cs
- Tests/SimpleTestCases/EscapeArgumentsVarName.cs
- Tests/SimpleTests.cs
- Tests/SimpleTests.csproj
Activated JS Strict mode for all generated files (#677).
This PR should be applied after #685, #688, #689 - otherwise some tests will fail.
> Strict mode

- Libraries/JSIL.Bootstrap.js
- Libraries/JSIL.Core.js
- Tests/FailingTestCases/DelegateMethod_Issue604.cs
- Tests/SimpleTestCases/DelegateDetached_Issue624.cs
- Tests/SimpleTests.csproj
- Tests/Tests.csproj
Two updates for delegate:
1. Support unbind form of delegate to instance method (so that we can pass instance as first argument).
2. Disabled guess of proper MethodInfo for interface delegate, as it works only in some conditions. We need to find beter solution here (we need some way to find method info in implementation based on methodinfo in declaration and implementation type). This logic should be written similar to the logic, that select correct method on call - but we need discuss how to reuse already existing code or refactor it for reuse.
This change need for interpreting some more complex expressions.
> Delegate update

- Libraries/JSIL.Bootstrap.Linq.js
- Libraries/JSIL.Bootstrap.js
- Libraries/JSIL.Core.Reflection.js
- Proxies/BCL/JSIL.Bootstrap.Linq.cs
- Tests/SimpleTestCases/Issue205.cs
- Tests/SimpleTestCasesForTranslatedBcl/ExpressionsTest.cs
- Tests/SimpleTests.csproj
Here is some staff, that I've found we need for correct work of Expressions. I have not added test for all this small changes, but will add some more complex Expressions test after this, #616 and some my future PR will be merged.
Changes here:
TypedConstantExpression simple implementation added.
op_Equality/op_Inequality for PropertyInfo and FieldInfo added.
Stub for Expression.Equal removed (as it just returned null) - we will use translated BCL version
Type.GetMethod additional overload added.
Interlocked.CompareExchange implementation added.
Probably we need add separate test for Interlocked.CompareExchange. If you merge it, lets create issue for it.
> Expression engine requirments

- Libraries/JSIL.Unsafe.js
- Tests/EmscriptenTestCases/IntPtrZeroEquality.cs
- Tests/EmscriptenTestCases/common/common.cpp
- Tests/Tests.csproj
This bug causes FNA to incorrectly believe the platform supports
more opengl functions than it actually does, because it can't
tell that the returned function pointers are null.
> Equality between null emscripten pointer and IntPtr.Zero

- Libraries/JSIL.Bootstrap.Text.js
- Tests/SimpleTestCases/StringCompare.cs
Fixed behavior for string.Compare(a, b) if a or b is null. (I haven't created issue for it).
> string.Compare against null.

- JSIL/AST/JSExpressionTypes.cs
- Tests/SimpleTestCases/Issue705.cs
- Tests/SimpleTests.csproj
Fix #705. Root cause of problem:
C# lock statement use temporary variable inside.
During transformation pass EliminateTemporaries, this temporary variable removed inside `EliminateSingleUseTemporaries.EliminateVariable` with next code:
```
var replacer = new VariableEliminator(
variable,
JSChangeTypeExpression.New(replaceWith, variable.GetActualType(TypeSystem), TypeSystem)
);
```
Than, nobody replace JSChangeTypeExpression with any other expression and `JavascriptAstEmitter` simple write inner expression, ignoring type changing:
```
public void VisitNode (JSChangeTypeExpression cte) {
Visit(cte.Expression);
}
```
I'm not sure, that I've fixed problem in best place - just added creation of `JSReadThroughReferenceExpression` inside `JSChangeTypeExpression.New` function. Maybe it should be …
> Failed to extract BoxedVariable before return result

- Compiler/Analyzers/DeadCodeAnalyzer/DeadCodeInfoProvider.cs
The DeadCodeAnalyzer will crash with a StackOverflowException and NullReferenceException when using this program:
```csharp
using System;
namespace ConsoleApplication2
{
class Base<T>
{
public override string ToString()
{
return "base";
}
}
class Class : Base<Class>
{
}
class Program
{
static void Main()
{
var instance = new Class();
Console.WriteLine(instance);
}
}
}
```
with this configuration:
```json
{
"AnalyzerSettings": {
"DeadCodeAnalyzer": {
"DeadCodeElimination": true
}
}
}
```
StackOverflowException is thrown when a type has a generic base type referring to the derived type.
NullReferenceException is thrown when the WhiteList value is either missing, `null`, or `[]`.
> Fix some crashes in DeadCodeAnalyzer

- Tests/EmscriptenTestCases/OutComplexUnionParameter.cs
- Tests/EmscriptenTestCases/common/common.cpp
- Tests/Tests.csproj
// C# output begins //
i=6 i2=9 f2=3.7000
// JavaScript output begins //
js> // Test output begins here //
// EXCEPTION:
TypeError: cachedInstance is undefined
// STACK:
Program_TestComplexUnion_Proxy_get_S@C:\Users\Jaiden\sq\JSIL\Libraries\JSIL.Core.js line 3285 > Function:8:3
Program_Main@C:\Users\Jaiden\sq\JSIL\Tests\EmscriptenTestCases\OutComplexUnionParameter.cs.out:32:64
runTestCase@C:\Users\Jaiden\sq\JSIL\Libraries\JSIL.Shell.js:175:5
runMain@typein:5:179
shellStartup@C:\Users\Jaiden\sq\JSIL\Libraries\JSIL.Shell.js:129:5
@typein:5:319
> Failing test case OutComplexUnionParameter

- Tests/Tests.csproj
- Tests/UnsafeTestCases/ZeroLengthIntArray.cs
A pointer to an array of zero width should be a null
pointer. Important for an odd edge case in emscripten
openal
> Failing test case for representation of int[0]

- JSIL/ILBlockTranslator.cs
- JSIL/JavascriptAstEmitter.cs
- Libraries/JSIL.Bootstrap.js
- Libraries/JSIL.Core.js
- Proxies/Object.cs
- Tests/SimpleTestCases/ObjectVirtualMethods.cs
- Tests/SimpleTests.csproj
- Tests/TestCases/DictionaryEnumerator.cs
- Tests/TestCases/DictionaryInterfaces.cs
Looks like I've found good enough solution for calling virtual object methods (Equals, GetHashCode) on raw JS types (string/int/double and so on).
For it I've added additional pseudo-calls to `JSReplacement` meta attribute:
- `$explicitThis(method)` - so we can pass information if we should do virtual call
- `$declaringType(method)` - so we can know method declaration type for non-virtual call.
With help of this new parameters, I changed instance virtual object methods with calling JSIL special helper functions, that know how to process raw-js object scenarios.
Test added.
After applying it we can remove hack with adding GetHashCode and Object_Equals method to string prototype - but for simplifying this PR I've not done it here.
> Object virtual methods

- Proxies/BCL/JSIL.Async.cs
Fixed missed BCL proxy for `System.Runtime.CompilerServices.AsyncTaskMethodBuilder`.
> Fixed missed BCL proxy for async task builder

- JSIL/TypeUtil.cs
This is fix for #758 - we need priory resolve type to pass through TypeForwardedTo.
> Compare types using type definition.

- JSIL/AssemblyTranslator.cs
- JSIL/JavascriptFormatter.cs
Fix #727.
JavascriptFormatter tried to use `$.TypeName` syntax for standard types in enclosed type context. If parent type was stripped to DCE, context is not enclosed anymore - so `$` is not defined.
@kg, probably it will be better always  pass $ as argument to `CreateEnum`/`CreateDelegate` and remove check for enclosed type? I had not tested it much, so don't know yet if there will be other problems.
> Fix declaring reference to built-in types from enclosed type with DCE

- Proxies/Net46.cs
- Proxies/Proxies.4.0.csproj
I've temporary excluded System.Resources.FastResourceComparer from translation.
Really we have an bug, that I'll report later. In:
```
internal static unsafe int CompareOrdinal(byte* a, int byteLen, string b)
{
int num1 = 0;
int num2 = 0;
int num3 = byteLen >> 1;
if (num3 > b.Length)
num3 = b.Length;
while (num2 < num3 && num1 == 0)
num1 = (int) (ushort) ((int) *a++ | (int) *a++ << 8) - (int) b[num2++];
if (num1 != 0)
return num1;
return byteLen - b.Length * 2;
}
```
translation of `*a++` produce `a++.get()` which is syntax error in JS strict mode.
> .Net Framework 4.6 compatibility fix

- Compiler/Analyzers/DeadCodeAnalyzer/DeadCodeInfoProvider.cs
- JSIL/AssemblyTranslator.cs
- Tests.DCE/DCETests/DCEMetaAttributes.cs
- Tests.DCE/DCETests/DCEMetaAttributesOnProxies.cs
- Tests.DCE/DCETests/StripOuterTypes.cs
- Tests.DCE/DeadCodeEliminationTest.cs
- Tests.DCE/Tests.DCE.csproj
Fixed processing of method arguments, generic parameters, return value and class generic parameters custom attributes (earlier was processed only if method/class has custom attributes).
Added initial support for MarshalInfo (#731) - for now added only CustomMarshalInfo (other may be easy added if needed - see ProcessMarshalInfo method).
We still need better test coverage for it all - but I'm not ready do it right now. Next step - improve proxy members processing.
> Dce improvements (continue)

- JSIL/ILBlockTranslator.cs
Should solve some more problems with #776, #768.
We still need to add some tests (see #777). Right now it may be a good idea to add Binary Test.
> Fixed Roslyn null comparison.

- JSIL.Libraries/Includes/Core/Reflection/Classes/System.Reflection.PropertyInfo.js
- JSIL.Libraries/Includes/Core/Reflection/Classes/System.Reflection.TypeInfo.js
- JSIL.Libraries/Includes/Core/Reflection/Classes/System.RuntimeType.js
- JSIL.Libraries/Includes/Core/Reflection/Classes/System.Type.js
- JSIL.Libraries/Includes/Core/Reflection/Main.js
- JSIL.Libraries/Includes/Core/Reflection/Utils/$jsilcore.MemberInfoExternals.js
- JSIL.Libraries/JSIL.Libraries.csproj
- JSIL.Libraries/Sources/JSIL.Core.js
- JSIL/AssemblyTranslator.cs
- Tests/ReflectionTestCases/GetInheritedAttributesFromMethods.cs
- Tests/Tests.csproj
1. Added System.Reflection.TypeInfo, System.RuntimeType derived from it now.
2. typeof(T).GetType() returns typeof(System.RuntimeType)
3. JSIL.GetMemberAttributes inherit support for MethodInfo.
4. GetConstructors always use DeclaredOnly internally (test added).
5. MemberInfo.IsDefined impelemented.
6. PropertyInfo GetValue/SetValue.
7. Type.IsClass implemented.
> Reflection additions

- Compiler/Analyzers/DeadCodeAnalyzer/JSIL.DeadCodeAnalyzer.csproj
- Compiler/Compiler.Executor.32bit.csproj
- Compiler/Compiler.csproj
- Compiler/Profiles/XNA4/Profiles.XNA4.csproj
- JSIL/JSIL.csproj
- Proxies/BCL/Proxies.Bcl.csproj
- Proxies/Proxies.4.0.csproj
- Proxies/XNA4/Proxies.XNA4.csproj
- Tests.DCE/Tests.DCE.csproj
- Tests/SimpleTests.csproj
- Tests/Tests.csproj
- Try/Try.csproj
Added restriction to C#5 features only for all our projects.
It should help prevent C#6 features usage under VS2015 as we still support VS2012 (#796).
> Restricted language features to C#5 (we still support VS2012).

- JSIL/AST/JSAstVisitor.cs
- JSIL/AST/JSNodeTypes.cs
- JSIL/AssemblyTranslator.cs
- JSIL/Configuration.cs
- JSIL/ILBlockTranslator.cs
- JSIL/JSIL.csproj
- JSIL/JavascriptAstEmitter.cs
- JSIL/JavascriptFormatter.cs
- JSIL/SourceMapBuilder.cs
- JSIL/TranslationResult.cs
Looks like I was able add some initial support of Source maps (#76). For now it was done not very clean and mostly hackish, but it already works in Chrome/IE/Visual Studio.
To enable their generation, user need add `BuildSourceMap : true` key in .jsilconfig.
> Source map initial support

- JSIL/Transforms/StaticAnalysis/EliminateSingleUseTemporaries.cs
- Tests/SimpleTestCasesForTranslatedBcl/Stack.cs
- Tests/SimpleTests.csproj
> EliminateTemporaries don't treat JSIndexerExpression as immutable

- JSIL/AST/JSLiteralTypes.cs
- JSIL/AST/JSNodeTypes.cs
- JSIL/JavascriptAstEmitter.cs
Use constructor to create decimal literals (#871). When we implement full decimal support we should change this, as we still load value through conversion to double.
> Create decimal literals through decimal constructor.

- JSIL.Libraries/Includes/Bootstrap/Core/Classes/System.Delegate.js
- JSIL.Libraries/Sources/JSIL.Core.js
- JSIL/AST/JSExpressionTypes.cs
- JSIL/ILBlockTranslator.cs
- JSIL/JavascriptAstEmitter.cs
- JSIL/SpecialIdentifiers.cs
- JSIL/Transforms/CacheSignatures.cs
- Tests/SimpleTestCases/DelegateOverload_Issue806.cs
- Tests/SimpleTestCases/Delegate_Issue875.cs
- Tests/SimpleTestCases/Delegate_Issue880.cs
- Tests/SimpleTests.csproj
Here is new delegate invocation implementation.
Now I store all required info (method owner, name, signature, if call is virtual) in JSIL.MethodPointerInfo, and use appropriate call through signature in JS part.
It fixes both #876 and #880.
Future work options (we may discuss it here, but will post them in separate PR):
1. Create methods in runtime to exclude `.apply` usage in delegate invocation (at least don't use it twice).
2. Probably move delegates created in run-time from MethodInfo to the same approach. MethodInfo invocation probably also worth to change same way to unify codebase.
Note: Looks like Mono was updated on Travis, and two tests fails now. It is not related to this PR.
> Delagate fixes

- JSIL.Libraries/Includes/Bootstrap/Text/Classes/System.Text.StringBuilder.js
The internal implementation function expected (self, string, startIndex,
count), but the bound methods both passed (self, startIndex, string,
count). The implementation would then insert the index at (usually) the
start of the string, which was not the desired behaviour.
> Correct argument order for StringBuilder.Insert

- JSIL.Libraries/Includes/Core/Types/Classes/System.ValueType.js
- JSIL.Libraries/Sources/JSIL.Core.js
- Tests/SimpleTestCases/StructHashCode.cs
- Tests/SimpleTests.csproj
Struct types should calculate their hash code based on their fields. Here it is implemented and test added.
> Correct implementation of GetHashCode for struct types.

- .travis.yml
- Tests/EvaluatorPool.cs
1. Disabled using of AppDomains in tests. Looks like it much more stable without them.
2. Changed artifacts upload script - it is possible to configure upload folder name now, use build date suffix for uploaded artifacts to preserve artifacts of rerun.
With this change, I can configure uploading build artifacts to my Yandex.Drive (publicly accessible https://yadi.sk/d/YnPDF_zfkzAbH). @kg, are you OK for me to update SQ/JSIL Travis-CI configuration after this PR will be merged?
> Travis fixes

- JSIL.Libraries/Sources/JSIL.Core.js
> JSIL.MakeTypeAlias check for same assembly prototype

- JSIL.Libraries/Includes/Bootstrap/Linq/Classes/System.Linq.Enumerable.js
- Tests/SimpleTestCases/EnumerableLast.cs
- Tests/SimpleTestCases/EnumerableSkip.cs
- Tests/SimpleTestCases/EnumerableZip.cs
- Tests/SimpleTests.csproj
Each of these methods is implemented and a test case added. Enumerable.Last has a special optimised case for lists, as the native implementation does, and the others produce a JSIL.AbstractEnumerable.
> Define Enumerable.{Zip,Skip,Last}

- JSIL.Libraries/Includes/Bootstrap/Async/Classes/System.Runtime.CompilerServices.AsyncTaskMethodBuilder.js
- JSIL.Libraries/Includes/Bootstrap/Async/Classes/System.Threading.Tasks.Task.js
Added usage of method signatures to avoid dynamic dispatching.
It is workaround for #915 until we implement proper fix for #916.
> Async updates

- Proxies/String.cs
- Tests/SimpleTestCases/StringJoinEnumerable.cs
This String.Join overload was not declared, although JSIL.JoinEnumerable
would already do the job if asked. This commit connects the two and
updates the existing test to cover the IEnumerable<String> case as well.
The other String.Join overloads are untouched.
> Implement String.Join(string, IEnumerable<string>)

- JSIL/AssemblyTranslator.cs
- JSIL/Configuration.cs
Implemented wrapping assembly in IIFE with references to other used assemblies (so assembly and manifest could be produced independently).
This feature is hidden under configuration parameter `InlineAssemblyReferences`.
This PR should open path for reusing of single-assembly translation, so it is possible to build some mechanics for translating one assembly per JSIL run.
> Assembly wrap in IIFE with references

- Compiler/Program.cs
Apply default config after all other configurations already loaded.
This PR fix #948.
> Apply default config after all other configurations already loaded

- JSIL/ILBlockTranslator.cs
Looks like yesterday in #973 I missed something. Here is corrected fix for #772.
> Correct fix for warning on roslyn-compiled struct field access.

- JSIL.Libraries/Sources/JSIL.Core.js
- JSIL/AssemblyTranslator.cs
- JSIL/Configuration.cs
- JSIL/JavascriptAssemblyEmitter.cs
- JSIL/JavascriptFormatter.cs
- JSIL/MethodSignature.cs
- JSIL/Transforms/CacheSignatures.cs
- JSIL/TypeUtil.cs
Here i implemented caching of open generic signatures (#970) and preserving only one signature cache per signature (896).
Both features are hidden under default settings.
(1) To enable global caching for open generic signatures user should change config:
CodeGenerator.PreferLocalCacheForGenericMethodSignatures=false
(2) To enable global caching for open generic interface method signatures user should change config:
CodeGenerator.PreferLocalCacheForGenericInterfaceMethodSignatures=false
(3) To enable storing only one method signature cache per signature:
CodeGenerator.CacheOneMethodSignaturePerMethod=false
I will still work more on method calls performance improvements, as all suggested option could either increase or decrease execution time dependent on usage scenario.
For my project I …
> Method signatures cache improvements

- JSIL.Libraries/.bin/git.cmd
- JSIL.Libraries/.bin/node.cmd
- JSIL.Libraries/.bin/npm.cmd
- JSIL.Libraries/JSIL.Libraries.csproj
- JSIL.Libraries/packages.config
- JSIL.sln
- Tests/Tests.csproj
- Tests/packages.config
Fixed clean build/rebuild under Visual Studio (problem was introduced when I've updated ILSpy).
Updated some NuGet packages to their latest verions.
> Fixed clean build/rebuild under VS, packages updated

- JSIL/ILBlockTranslator.cs
- Tests/SimpleTestCases/BoxNumeric_Issue981.cs
- Tests/SimpleTests.csproj
Fixed incorrect numeric type boxing (#981).
Use Box type argument to determine wrap type for raw types.
> Fixed incorrect numeric type boxing

- JSIL.Libraries/Sources/JSIL.Core.js
Use `JSIL.SetValueProperty` for `"__ElementType__"` array property.
It restore functionality of JSON.stringify with JSIL-created arrays (as `__ElementType__` mark as non-enumerable)
> Array JSON.stringify interop fixed

- Compiler/Configuration.cs
- Compiler/Extensibility/IProfile.cs
- Compiler/Profiles/Base.cs
- Compiler/Profiles/Default.cs
- Compiler/Profiles/XNA4/XNA4Profile.cs
- Compiler/Program.cs
- JSIL.Libraries/Sources/JSIL.Core.js
- JSIL.mscorlib/JSIL.mscorlib.dll.jsilconfig
- JSIL.mscorlib/Properties/AssemblyInfo.cs
- JSIL/AssemblyManifest.cs
- JSIL/AssemblyTranslator.cs
- JSIL/Configuration.cs
- JSIL/DefinitelyTypedAssemblyEmitter.cs
- JSIL/Extensibility/Emitter.cs
- JSIL/JS Libraries/DefinitelyTyped/internals/JSIL.Core.d.ts
- JSIL/JS Libraries/DefinitelyTyped/module.JSIL.Core.d.ts
- JSIL/JS Libraries/DefinitelyTyped/module.JSIL.Core.js
- JSIL/JSIL.csproj
- JSIL/JavascriptAssemblyEmitter.cs
- JSIL/JavascriptFormatter.cs
- JSIL/TranslationResult.cs
- Tests/ComparisonTest.cs
- Tests/MetadataTests.cs
- Try/SnippetCompiler.cs
Initial implementation of TypeScript DefinitelyTyped mappings for translated code.
It is implemented as separate emitter. To enable, jsilconfig should contain: `"EmitterFactories" : ["JavascriptEmitterGroupFactory", "DefinitelyTypedEmitterGroupFactory"]`
When enabled, for each assembly additionally created 3 files:
- `module.%assemblyName%.d.ts`
- `module.%assemblyName%.js`
- `internals\%assemblyName%.d.ts`
And additionally:
- `module.JSIL.Core.d.ts`
- `module.JSIL.Core.js`
- `internals\JSIL.Core.d.ts`
JS file is just a wrapper on top of `JSIL.GetAssembly(...)` in node.js module format.
To use type definition user should reference `module.%assemblyName%`.
What's to do next:
- Introduce test framework and cover with test cases
- Discuss if we need wrap IEmitterGroupFactory[] and …
> TypeScript DefinitelyTyped support

- JSIL.Libraries/Includes/Bootstrap/Core/Classes/System.Convert.js
- JSIL.mscorlib/Imports.cs
A little bit dirty `System.Convert.ToBase64CharArray` implementation based on existing `ToBase64String`
> System.Convert.ToBase64CharArray

- Compiler/SolutionBuilder.cs
> Use same executable for out-of-process build

- JSIL.Libraries/Includes/Core/Reflection/Classes/System.Reflection.Assembly.js
- JSIL.Libraries/Includes/Core/Reflection/Helpers/JSIL.ReflectionGetTypeInternal.js
- Tests/SimpleTestCases/GetTypeFromAssembly_Issue1035.cs
- Tests/SimpleTests.csproj
Issue #1035 was fixed. Test was added.
> Assembly.GetType fixed

- JSIL/ILBlockTranslator.cs
- JSIL/TypeUtil.cs
- Tests/SimpleTestCases/ble.un.il
- Tests/SimpleTests.csproj
> Support for unsigned comparison
